### ISSUE TITLE
Can't rebuild release even with good RAR version

### ISSUE THREAD

**Issue by MRiCEQB** [srrDB/pyrescene#7]
I'm trying to rebuild Sega_Rally_v2_EUR_PSP-PLAYASiA, got a matching ISO and the latest pyRescene (as of November 20th).
But I always get the following error - any ideas?

`C:\pyReScene\bin\windows>pysrr.bat "E:\tmp\Sega Rally srr\Sega_Rally_v2_EUR_PSP-PLAYASiA.srr" -ypri "E:\tmp\Sega Rally srr\work" -o "E:\tmp\Sega Rally srr\Sega_Rally_v2_EUR_PSP-PLAYASiA" -z C:\Users\iCEQB\Desktop\srrgui-1.3\RARTRY\ -t "E:\tmp\Sega Rally srr\temp"
SRR file created with pyReScene Auto 0.4.
Re-creating stored file: pa-segarl2.nfo
Re-creating stored file: pa-segarl2.sfv
Re-creating RAR file: pa-segarl2.rar
Trying to rebuild compressed file pa-segarl2.iso.
Grabbing large enough data piece size for testing.
Trying 2012-06-09 4.20.
Good RAR version detected: 2012-06-09 4.20
C:\Users\iCEQB\Desktop\srrgui-1.3\RARTRY\2012-06-09_rar420.exe a -m5 -mdG -s- -ds -mt1 -vn -o+ -ep -idcd -v22564569b E:\tmp\Sega Rally srr\temp\SRR-n_yj3r4y\pyReScene_com
pressed.rar E:\tmp\Sega Rally srr\work\pa-segarl2.iso
Compressing pa-segarl2.iso...

Evaluation copy. Please register.

Creating archive E:\tmp\Sega Rally srr\temp\SRR-n_yj3r4y\pyReScene_compressed.rar

Adding    E:\tmp\Sega Rally srr\work\pa-segarl2.iso
Calculating the control sum

Creating archive E:\tmp\Sega Rally srr\temp\SRR-n_yj3r4y\pyReScene_compressed.r00

...       pa-segarl2.iso
Calculating the control sum

Creating archive E:\tmp\Sega Rally srr\temp\SRR-n_yj3r4y\pyReScene_compressed.r01

...       pa-segarl2.iso
Calculating the control sum

Creating archive E:\tmp\Sega Rally srr\temp\SRR-n_yj3r4y\pyReScene_compressed.r02

...       pa-segarl2.iso
Calculating the control sum

Creating archive E:\tmp\Sega Rally srr\temp\SRR-n_yj3r4y\pyReScene_compressed.r03

...       pa-segarl2.iso
Calculating the control sum

Creating archive E:\tmp\Sega Rally srr\temp\SRR-n_yj3r4y\pyReScene_compressed.r04

...       pa-segarl2.iso
Calculating the control sum

Creating archive E:\tmp\Sega Rally srr\temp\SRR-n_yj3r4y\pyReScene_compressed.r05

...       pa-segarl2.iso
Calculating the control sum

Creating archive E:\tmp\Sega Rally srr\temp\SRR-n_yj3r4y\pyReScene_compressed.r06

...       pa-segarl2.iso                                              OK
Calculating the control sum
160199729
160199984
Still not fine :(.
Traceback (most recent call last):
  File "C:\pyReScene\rescene\srr.py", line 605, in main
    parser.exit(manage_srr(options, infolder, infiles, working_dir))
  File "C:\pyReScene\rescene\srr.py", line 319, in manage_srr
    options.volume is None, options.volume, rar_mt)
  File "C:\pyReScene\rescene\main.py", line 1332, in reconstruct
    in_folder, hints, auto_locate_renamed)
  File "C:\pyReScene\rescene\main.py", line 1722, in get_rar_data_object
    auto_locate_renamed))
  File "C:\pyReScene\rescene\main.py", line 2044, in compressed_rar_file_factory
    nblock, followup_src, solid=False)
  File "C:\pyReScene\rescene\main.py", line 2237, in __init__
    raise ValueError("Still not fine :(.")
ValueError: Still not fine :(.
Unexpected Error: Still not fine :(.
C:\pyReScene\bin\windows>`

**Comment by itzoke** [comment]
Try different values for the `-mt` flag

**Comment by itzoke** [comment]
`srr.py` accepts the following options with regards to threads
```
  Compressed reconstruction options:
    Set the rar -mt thread parameter to exclude certain possibilities when
    reconstructing compressed RARs.

    --mt-set=MT_SET     list of possible thread values. e.g. 4,6,8
    --mt-min=MT_MIN     minimum thread count to try. e.g. 24
    --mt-max=MT_MAX     maximum thread count to try. e.g. 2
    --mt-common         same as --mt-set 1,2,4,6,8,12,16,24,32
```
