### ISSUE TITLE
Can't rebuild RELOADED release

### ISSUE THREAD

**Issue by MRiCEQB** [srrDB/pyrescene#9]
Hi all,

I'm trying to rebuild Splinter.Cell.Chaos.Theory-RELOADED but none of the RAR versions (184 version tried) match the packer that RELOADED used.
I read that RELOADED used some kind of custom packer and that this issue has been resolved in 2016 (https://bitbucket.org/Gfy/pyrescene/issues/107/hi2u-and-reloaded-rar-files).
Is there any flag that forces pyRescene to try the RELOADED modifications while testing for a compatible RAR version?
I saw in the source code that it was tested with Street.Fighter.V-RELOADED, which was released 10 years after Splinter.Cell.Chaos.Theory-RELOADED - so I hoped that Splinter Cell won't be an issue.
I am using the latest commit as of this writing and I currently don't know what to do from here :(

**Comment by itzoke** [comment]
> Splinter.Cell.Chaos.Theory-RELOADED

Is compressed using RAR5 which is not supported.

**Comment by MRiCEQB** [comment]
> > Splinter.Cell.Chaos.Theory-RELOADED
> 
> Is compressed using RAR5 which is not supported.

The release was pred on may 26th 2006
RAR5 was released in April 2013

**Comment by itzoke** [comment]
So it seems we have an incorrect detection of RAR5.
```
Grabbing large enough data piece size for testing.
RAR5 files are not yet supported!
```

**Comment by MRiCEQB** [comment]
That's strange, I never got this error on my end.
pyReScene tried like all exe files I had and just came to the conclusion that it can't find a suitable version to rebuilt this release.

**Comment by itzoke** [comment]
It seems to be related to which rar versions are in the preprar folder. Removing any version >= 5.50 resolves that part. Looks like the `-ma4` flag isn't correctly set

**Comment by itzoke** [comment]
It seems that this is just one of those releases that won't rescene (some work on a specific OS only).
